### criar médicos
POST http://localhost:8080/medicos
Content-Type: application/json

{
  "nome": "Médico Teste 1",
  "email": "medico.teste1@voll.med",
  "telefone": "(11)11111-1111",
  "crm": "111111",
  "especialidade": "ORTOPEDIA",
  "endereco": {
    "logradouro": "rua 1",
    "bairro": "bairro 1",
    "cep": "11111111",
    "cidade": "cidade 1",
    "uf": "U1",
    "numero": "1",
    "complemento": "complemento 1"
  }
}

### listar médicos
GET http://localhost:8080/medicos

### atualizar médicos
PUT http://localhost:8080/medicos
Content-Type: application/json

{
  "id": 5,
  "nome": "Médico Teste 5"
}

### excluir médicos
DELETE http://localhost:8080/medicos/5

###